events = [
    {
        'name': 'Lasergamen',
        'desc': 'In Amersfoort een uurtje lasergamen met max. 13 personen... wie wil dat nou niet?',
        'yes': ['Brom', 'Egdar', 'Mork'],
        'probably': ['Meesje'],
        'maybe': ['Riineer'],
        'hmm': [],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Een cafeetje pakken',
        'desc': 'Een drankje doen met je matties in een heerlijk café.',
        'yes': ['Egdar'],
        'probably': ['Riineer', 'Mork', 'Meesje'],
        'maybe': ['Brom'],
        'hmm': [],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Spelletjes spelen',
        'desc': 'Lekker met zijn allen een avondje spelletjes spelen bij iemand thuis!',
        'yes': ['Brom', 'Riineer', 'Meesje'],
        'probably': ['Egdar', 'Mork'],
        'maybe': [],
        'hmm': [],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Sietse helpen daten',
        'desc': 'Sietse is alleen, eenzaam en single. Wie helpt hem aan een vriendin? en Bram is Gay.',
        'yes': ['Meesje'],
        'probably': ['Riineer', 'Egdar'],
        'maybe': ['Brom'],
        'hmm': ['Mork'],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Escape room',
        'desc': 'Wat is er nou leuker dan een escape room doen? Het staat al zo lang in ons vizier, tijd om het nu ECHT te doen!',
        'yes': ['Brom', 'Mork', 'Meesje'],
        'probably': ['Egdar'],
        'maybe': ['Riineer'],
        'hmm': [],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Bram helpen klussen',
        'desc': 'Bram heeft een nieuwe kamer... wie zou hem nou niet willen ondersteunen in het opknappen van zijn kamer?',
        'yes': ['Brom', 'Mork'],
        'probably': ['Riineer'],
        'maybe': ['Egdar'],
        'hmm': ['Meesje'],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Niks doen',
        'desc': 'Soms kan het zo simpel zijn.',
        'yes': ['Mork', 'Meesje'],
        'probably': ['Egdar'],
        'maybe': ['Riineer'],
        'hmm': ['Brom'],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Picknick en zwemmen',
        'desc': 'Zeg nou zelf, wat is er leuker op een warme zomerdag dan gezellig picknicken en af en toe zwemmen op een prachtige locatie?',
        'yes': ['Riineer'],
        'probably': ['Meesje'],
        'maybe': ['Brom'],
        'hmm': ['Egdar'],
        'no': ['Mork'],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'LAN Party',
        'desc': 'De mensen die hieraan meegedaan hebben, kunnen in geuren en kleuren vertellen hoe leuk het is; spelletjes spelen, maar dan digitaal! Niets is leuker dan je kapot lachen bij het spelen van debiele spelletjes, het competitief spelen van een shooter of het proberen samen te werken in een klungelige cooperative game.',
        'yes': ['Brom', 'Egdar', 'Meesje'],
        'probably': ['Mork'],
        'maybe': [],
        'hmm': [],
        'no': ['Riineer'],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Poulen',
        'desc': 'Het is een relaxte bezigheid, maar wie zou er nou niet willen chillen met ballen en stokken?',
        'yes': [],
        'probably': ['Brom', 'Mork', 'Meesje'],
        'maybe': ['Riineer', 'Egdar'],
        'hmm': [],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Hackathon',
        'desc': 'De Spyfall website waar we ons NU op bevinden - is best wel een troep. Het idee om terug te gaan, nog een poging te wagen en menig hart te verblijden, zal iedereen gelukkig maken.',
        'yes': ['Brom', 'Mork'],
        'probably': [],
        'maybe': [],
        'hmm': ['Meesje'],
        'no': ['Riineer', 'Egdar'],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'DnD Oneshot',
        'desc': 'Voor de D&D liefhebbers is er niets leukers dan te proberen een klein avontuur te beleven met hun favoriete X-Files vrienden!',
        'yes': ['Brom', 'Meesje'],
        'probably': ['Egdar', 'Mork'],
        'maybe': [],
        'hmm': ['Riineer'],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey"],
    },
    {
        'name': 'Minecraft Marathon',
        'desc': 'Laat je verbazen hoe leuk het kan zijn om te proberen een halve dag te overleven in een simpel spelletje zoals Minecraft. Team building, eindeloze gesprekken tijdens het werken en rustige samenwerkingen gegarandeerd!',
        'yes': ['Brom', 'Meesje'],
        'probably': [],
        'maybe': ['Mork'],
        'hmm': ['Egdar'],
        'no': [],
        'NA': ["Harissa", "Swammy", "Seneca", "Mickey", "Riineer"],
    },
    {
        'name': 'Picknick en NIET zwemmen',
        'desc': 'Zeg nou zelf, wat is er leuker op een warme zomerdag dan gezellig picknicken - en de germaphobes blij te maken door niet in het water te springen?',
        'yes': ['Meesje'],
        'probably': ['Mork'],
        'maybe': [],
        'hmm': ['Brom'],
        'no': [],
        'NA': ['Egdar', 'Riineer', "Harissa", "Swammy", "Seneca", "Mickey"],
    }
]

def calculate_event_score(event):
    score = 4*event['yes'] + 3*event['probably'] + 2*event['maybe'] + event['hmm']
    total = 4*(event['yes'] + event['probably'] + event['maybe'] + 
        event['hmm'] + event['no'] + event['NA']
    )
    
    return score/total